name: Build and Deploy Prerelease to Netlify
on:
    release:
        types: [prereleased]

env:
    VERSION: 0.1.0 #update version here

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                ref: main

            - name: Build Number Generator
              uses: einaregilsson/build-number@v3
              with:
                  token: ${{ github.token }}

            - name: "Setup Node.js"
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: "Bump version"
              run: npm version $VERSION-$BUILD_NUMBER-rc --git-tag-version=false

            - name: "Install dependencies"
              run: npm install

            - name: 'Create env file'
              run: |
                touch .env
                echo VITE_X_API_KEY=${{ secrets.BETA_X_API_KEY }} >> .env
                echo VITE_CLIENT_ID=${{ secrets.BETA_CLIENT_ID }} >> .env
                echo VITE_CLIENT_SECRET=${{ secrets.BETA_CLIENT_SECRET }} >> .env

            - name: "Build webapp"
              run: npm run build

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                projectName: 'd2bountytracker-beta'
                directory: 'dist'
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
