name: Build and Deploy Prerelease to Netlify
on:
    release:
        types: [prereleased]

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: "Setup Node.js"
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: "Install dependencies"
              run: npm install
            - name: "Install netlify cli"
              run: npm i netlify-cli
            - name: "Link to netlify site"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify link --id=${{ secrets.NETLIFY_BETA_SITE_ID }}
            - name: "Setup env variables"
              run: |
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set CLIENT_ID ${{ secrets.BETA_CLIENT_ID }} \
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set CLIENT_SECRET ${{ secrets.BETA_CLIENT_SECRET }} \
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set X_API_KEY ${{ secrets.BETA_X_API_KEY }}
            - name: "Build source code"
              run: npm run build
            - name: Deploy to Netlify
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify deploy --dir='public' --message="Prerelease deploy v${{ github.ref }}" --prod
