name: Build and Deploy Release to Netlify
on:
    release:
        types: [released, prerelease]

env:
    VERSION: 0.1.0 #update version here

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build Number Generator
              uses: einaregilsson/build-number@v3
              with:
                  token: ${{ github.token }}

            - name: "Setup Node.js"
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: "Bump version"
              run: npm version $VERSION-$BUILD_NUMBER --git-tag-version=false

            - name: "Install dependencies"
              run: npm install

            - name: "Install netlify cli"
              run: npm i -g netlify-cli

            - name: "Link to netlify site"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify link --id=${{ secrets.NETLIFY_SITE_ID }}

            - name: "Setup env variables - VITE_CLIENT_ID"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set VITE_CLIENT_ID ${{ secrets.BETA_CLIENT_ID }}

            - name: "Setup env variables - VITE_CLIENT_SECRET"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set VITE_CLIENT_SECRET ${{ secrets.BETA_CLIENT_SECRET }}

            - name: "Setup env variables - VITE_X_API_KEY"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set VITE_X_API_KEY ${{ secrets.BETA_X_API_KEY }}

            - name: Deploy to Netlify
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify deploy --dir='dist' --message="Release deploy v${{ github.ref }}" --build --prod
