name: Build and Deploy Release to Netlify
on:
    release:
        types: [released]

jobs:
    setup:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: "Setup Node.js"
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: "Install dependencies"
              run: npm install
            - name: "Install netlify cli"
              run: npm i netlify-cli
            - name: "Link to netlify site"
              run: netlify link ${{ secrets.NETLIFY_SITE_ID }}
            - name: "Setup env variables"
              run: |
                  netlify env:set CLIENT_ID ${{ secrets.CLIENT_ID }} \
                  netlify env:set CLIENT_SECRET ${{ secrets.CLIENT_SECRET }} \
                  netlify env:set X_API_KEY ${{ secret.X_API_KEY }}
    build:
        needs: setup
        runs-on: ubuntu-18.04
        steps:
            - name: "Build source code"
              run: npm run build
            - name: Deploy to Netlify
              run: netlify deploy --dir='public' --message="Release deploy v${{ github.ref }}" --prod
