name: Build and Deploy Release to Netlify
on:
    release:
        types: [released, prerelease]

env:
    VERSION: 0.1.0 #update version here

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: "Setup Node.js"
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: "Bump version"
              run: npm version $VERSION-$BUILD_NUMBER --git-tag-version=false

            - name: "Install dependencies"
              run: npm install

            - name: "Install netlify cli"
              run: npm i -g netlify-cli

            - name: "Link to netlify site"
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify link --id=${{ secrets.NETLIFY_SITE_ID }}

            - name: "Setup env variables"
              run: |
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set CLIENT_ID ${{ secrets.CLIENT_ID }} \
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set CLIENT_SECRET ${{ secrets.CLIENT_SECRET }} \
                  NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify env:set X_API_KEY ${{ secrets.X_API_KEY }}

            - name: Deploy to Netlify
              run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify deploy --dir='public' --message="Release deploy v${{ github.ref }}" --build --prod
